#! /bin/bash

### BEGIN INIT INFO
# Provides:          chkphy
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Check BBB phy on boot and repower if PHY failed
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

# The following part always gets executed.

# check if this is our first time waking
# by checking if the wake register has already been set
# by a previous boot

if (( $(bbbrtc sleep) != 110 )); then 
     echo "Rebooting" >>/var/tmp/chkphy.log
     # make sure that  message actually gets written before we pull the plug
     sync
     i2cset -f -y 0 0x24 0x0a 0x00
     bbbrtc now 130
     bbbrtc wake 120
     bbbrtc sleep 110
     bbbrtc now 100
else
     echo "Already booted" >>/var/tmp/chkphy.log	 
fi
